GET https://login-backend-ybx2.onrender.com

##########

POST https://login-backend-ybx2.onrender.com/register
Content-Type: application/json

{
    "name":"louis","password":"mango"
}

#####

POST https://login-backend-ybx2.onrender.com/login
Content-Type: application/json

{
    "name":"louis","password":"mango"
}

#####

POST https://login-backend-ybx2.onrender.com/logout
Content-Type: application/json

#####

POST https://login-backend-ybx2.onrender.com/logout
Content-Type: application/json

{
    "name":"louis","password":"mango"
}